language: android

jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
  licenses:
    - android-sdk-license-.+

before_install:
 - yes | sdkmanager "platforms;android-28"
 - chmod +x gradlew
